"""save query text

Revision ID: 149ead18efba
Revises: 279f2a1227a3
Create Date: 2022-08-17 19:44:24.483820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '149ead18efba'
down_revision = '279f2a1227a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_metrics', sa.Column('query_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_metrics', 'query_string')
    # ### end Alembic commands ###
