"""workspace in ImageMetadata

Revision ID: 1f19fc3f8361
Revises: d8cc52386845
Create Date: 2022-08-18 08:57:24.826470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f19fc3f8361'
down_revision = 'd8cc52386845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_metadata', sa.Column('workspace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images_metadata', 'workspace')
    # ### end Alembic commands ###
