"""channel in query metrics

Revision ID: 279f2a1227a3
Revises: 4e3e2fade921
Create Date: 2022-08-17 14:31:05.545188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '279f2a1227a3'
down_revision = '4e3e2fade921'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_metrics', sa.Column('channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_metrics', 'channel')
    # ### end Alembic commands ###
