"""query metrics id list and isSuccessful

Revision ID: 4e3e2fade921
Revises: 91cfd1a5cf8b
Create Date: 2022-08-17 14:13:34.096538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e3e2fade921'
down_revision = '91cfd1a5cf8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_metrics', sa.Column('last_image_index', sa.Integer(), nullable=False))
    op.add_column('query_metrics', sa.Column('successful', sa.Boolean(), nullable=False))
    op.add_column('query_metrics', sa.Column('query_result_ids', sa.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_metrics', 'query_result_ids')
    op.drop_column('query_metrics', 'successful')
    op.drop_column('query_metrics', 'last_image_index')
    # ### end Alembic commands ###
