"""add tables 2

Revision ID: e3fe3a19dda9
Revises: d0780bcc7cd2
Create Date: 2022-07-03 19:23:19.486389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fe3a19dda9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.Column('image_text', sa.String(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_metrics')
    op.drop_table('images_metadata')
    # ### end Alembic commands ###
